services:
  app:
    image: beenguyen0601/english-class-fe:prod
    container_name: english-class-fe
    restart: unless-stopped

    env_file:
      - .env

    networks:
      - app-net

networks:
  app-net:
    external: true